Repository bitcoin-stark/khepri-starknet, pull requests merged in 2022-06, with the labels that each got.

#24 📝 add a doc about header consensus rules
  docs/bitcoin/block_header_validation_rules.md
Labels: Type: documentation, Difficulty: intermediate, Duration: under a day, Context: isolated

#27 📝 add links to issues
  docs/bitcoin/block_header_validation_rules.md
Labels: Type: documentation

#34 Add encode_target implementation
  src/header/library.cairo
  src/header/rules/check_pow.cairo
  src/utils/target.cairo
  src/utils/test_target.cairo
Labels: Context: coupled, Difficulty: intermediate, State: review
